import pymongo

client = pymongo.MongoClient("mongodb://localhost:27017/")

mydb = client["mongo_python_demo"]  # Create databse

coll = mydb["users"]    # Create collection



#--------- Insert One ---------#


# To insert a record or document in collection, we use 'insert_one()' method. 
# Which contains dictinories of name and value pair of each the document

mydict = {"name" : "Andrew", "city" : "Peris"}

# The insert_one() method returns a InsertOneResult object
x = coll.insert_one(mydict)     # Insert one document(record)

print(x)    # Printing object of the insert query

# The insert_one() method returns a InsertOneResult object, which has a property, inserted_id, that holds the id of the inserted document
print(x.inserted_id)    # Which is uniquely generated by MongoDB itself. 




#------------ Insert Many ---------#

# To insert multiple documents into a collection in MongoDB, we use the insert_many() method.

# The first parameter of the insert_many() method is a list containing dictionaries with the data you want to insert
my_dict = [
    {"name" : "Rakesh", "city" : "Mumbai"},
    {"name" : "Ricky", "city" : "Sidney"},
    {"name" : "Joe", "city" : "Landon"},
    {"name" : "Jam Paul", "city" : "Darban"}
    ]

# The insert_many() method returns a InsertManyResult object
x =  coll.insert_many(my_dict)  # Insert many document(record)

# The insert_many() method returns a InsertManyResult object, which has a property, inserted_ids, that holds the ids of the inserted documents.
#print list of the _id values of the inserted documents:
print(x.inserted_ids)




#----------- Insert with specified '_id' -----------------#

# If you do not want MongoDB to assign unique ids for you document, you can specify the _id field when you insert the documents.
# Note: Two documents cannot have the same _id.

my_dict = [
    {"_id" : 1, "name" : "Kevin", "city" : "Bangalore"},
    {"_id" : 2, "name" : "Brandon", "city" : "Wellington"},
    {"_id" : 3, "name" : "Raza", "city" : "Qatar"},
    {"_id" : 4, "name" : "James", "city" : "New York"}
]

x = coll.insert_many(my_dict)   # Insert many docements

print(x.inserted_ids)   # Prints ids of inserted records in the list
